language: php

php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'

#env:
#    secure: 'fahV+AjOpZzSsleCp2CJcieuL+t8WkeDXTt4dDiobfbvDKycu0jyKfBG3x04YMpL3ic+zYTSELyFtDLVDY5nd2aNvi0fPpgiMkCp4YxhXfRL8d0GvOSYoSEXwIQieTZ1F6+Rn7/19db3APFnHywXAie2cI8sKUIvEbAIefycOLQ='

before_install: composer install

script: ./vendor/bin/phpunit --configuration test/unit --coverage-clover coverage.xml

after_success:
    - 'bash <(curl --silent https://codecov.io/bash)'
